server:
   port: 8081

spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/NewSpringBootDB
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver   # Add this line

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: false
      properties:
         hibernate:
            format_sql: true

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
management:
   tracing:
      sampling:
         probablity: 1.0